(function(a,e){function v(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function m(f,e){if(!f)return{};var b="INFO"===e.logLevel;f.m&&f.m.message&&(f=f.m);var g=e.m||e.message||"",g=f.m&&f.m.message?g+f.m.message:f.m&&f.m.target&&f.m.target.tagName?g+("Error handler invoked by "+f.m.target.tagName+" tag"):f.m?g+f.m:f.message?g+f.message:g+"Unknown error",g={m:g,name:f.name,type:f.type,csm:P+" "+(f.fromOnError?"onerror":"ueLogError")},d,r,k=0,l;g.logLevel=e.logLevel||B;e.adb&&(g.adb=e.adb);if(d=e.attribution)g.attribution=
""+d;if(!b){g.pageURL=e.pageURL||""+(window.location?window.location.href:"")||"missing";g.f=f.f||f.sourceURL||f.fileName||f.filename||f.m&&f.m.target&&f.m.target.src;g.l=f.l||f.line||f.lineno||f.lineNumber;g.c=f.c?""+f.c:f.c;g.s=[];g.t=a.ue.d();if((b=f.stack||(f.err?f.err.stack:""))&&b.split)for(g.csm+=" stack",d=b.split("\n");k<d.length&&g.s.length<K;)(b=d[k++])&&g.s.push(v(b));else for(g.csm+=" callee",r=z(f.args||arguments,"callee"),d=k=0;r&&k<K;)l=A,r.skipTrace||(b=r.toString())&&b.substr&&(l=
0===d?4*A:l,l=1==d?2*A:l,g.s.push(b.substr(0,l)),d++),r=z(r,"caller"),k++;if(!g.f&&0<g.s.length&&(k=g)&&k.s){var m,b=0<k.s.length?k.s[0]:"";d=1<k.s.length?k.s[1]:"";b&&(m=b.match(y));m&&3==m.length||!d||(m=d.match(n));m&&3==m.length&&(k.f=m[1],k.l=m[2])}}return g}function z(a,e){try{return a[e]}catch(b){}}function w(f,n){if(f){var b=m(f,n),g=window.ue_err?window.ue_err.addContextInfo:null;g&&g(b);a.ue.log(b,n.channel||l,{nb:1});"function"===typeof ue_err.elh&&ue_err.elh(f,n);try{if(!f.fromOnError){var d=
e.console,r=e.JSON,g="Error logged with the Track\x26Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(d){if(r&&r.stringify)try{g+=r.stringify(b)}catch(k){g+="no info provided; converting to string failed"}else g+=b.m;"function"===typeof d.error?d.error(g,b):"function"===typeof d.log&&d.log(g,b)}}}catch(k){}}}function G(f,e){if(f&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ter.push(f);e=e||{};var b=f.logLevel||e.logLevel;e.logLevel=b;e.attribution=f.attribution||e.attribution;b&&
b!==B&&b!==L&&b!==C&&b!==H||a.ue_err.ec++;b&&b!=B||ue_err.ecf++;w(f,e)}}if(a.ue_err&&(!a.ueLogError||a.ueLogError.isStub)){var l=a.ue_err_chan||"jserr",B="FATAL",L="ERROR",C="WARN",H="DOWNGRADED",P="v5",K=20,A=256,n=/\(?([^\s]*):(\d+):\d+\)?/,y=/.*@(.*):(\d*)/;w.skipTrace=1;m.skipTrace=1;G.skipTrace=1;(function(){if(a.ue_err.erl){var f=a.ue_err.erl.length,e,b;for(e=0;e<f;e++)b=a.ue_err.erl[e],w(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=G}})(ue_csm,window);
(function(a,e){function v(a){for(var c={},h,b,p=0;p<a.length;p++)b=a[p],h=b.r+b.s+b.m,b.c&&(c[h]||(c[h]=[]),c[h].push(a[p]));return c}function m(a){for(var c=1;c<arguments.length;c++){var h=arguments[c];try{if(h.isSupported)return h.send(a)}catch(b){}}}function z(){if(d.length){for(var a=0;a<k.length;a++)k[a]();b._flhs+=1;w();m(v(d.splice(0,d.length)),M,D,E)}Q=F=0}function w(){A&&G({k:"chk",f:b._flhs,l:b._lpn,s:"full"},"csm")}function G(t,c,h){h=h||{};!a.ue_furl||0===h.bf&&b.isBF||(t={r:h.r||b.rid,
s:h.s||a.ue_sid,m:h.m||a.ue_mid,mkt:h.mkt||a.ue_mkt,sn:h.sn||a.ue_sn,c:c,d:t,t:h.t||b.d(),cs:h.c&&a.ue_qsl},b._lpn[c]=(b._lpn[c]||0)+1,h.b?m(v([t]),M,E):h.nb?m(v([t]),M,D,E):h.img||R[c]?m(v([t]),E):h.ff?(d.push(t),z()):h.n?(d.push(t),0===O?z():Q||(Q=e.setTimeout(z,O))):(d.push(t),F||(F=e.setTimeout(z,N))))}function l(a,c,h){I++;I==K&&G({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},e.ue_err_chan||"jserr");(I<K||h&&h.il)&&G(a,c,h)}function B(){if(!J){for(var a=0;a<
r.length;a++)r[a]();for(a=0;a<k.length;a++)k[a]();b._flhs+=1;w();m(v(d.splice(0,d.length)),M,E);J=!0}}function L(a){var c=f(a);window.ue_fps&&a.reqs&&(c={csmcount:{counter:n,t:0,value:c.length}},c.csmcount.value+=f(c).length,a.reqs.push(c),c=f(a));return c}var C={};(function(){function a(c){return 10>c?"0"+c:c}function c(c){b.lastIndex=0;return b.test(c)?'"'+c.replace(b,function(c){var a=e[c];return"string"===typeof a?a:"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+c+'"'}function h(a,
b){var e,x,t=p,q,d=b[a];d&&"object"===typeof d&&"function"===typeof d.toJSON&&(d=d.toJSON(a));"function"===typeof g&&(d=g.call(b,a,d));switch(typeof d){case "string":return c(d);case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";p+=f;q=[];if("[object Array]"===Object.prototype.toString.apply(d)){b=d.length;for(a=0;a<b;a+=1)q[a]=h(a,d)||"null";x=0===q.length?"[]":p?"[\n"+p+q.join(",\n"+p)+"\n"+t+"]":"["+q.join(",")+"]";p=t;
return x}if(g&&"object"===typeof g)for(b=g.length,a=0;a<b;a+=1)"string"===typeof g[a]&&(e=g[a],(x=h(e,d))&&q.push(c(e)+(p?": ":":")+x));else for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(x=h(e,d))&&q.push(c(e)+(p?": ":":")+x);x=0===q.length?"{}":p?"{\n"+p+q.join(",\n"+p)+"\n"+t+"}":"{"+q.join(",")+"}";p=t;return x}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(c){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+
"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(c){return this.valueOf()});var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,p,f,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;"function"!==typeof C.stringify&&(C.stringify=function(c,a,b){var e;f=p="";if("number"===
typeof b)for(e=0;e<b;e+=1)f+=" ";else"string"===typeof b&&(f=b);if((g=a)&&"function"!==typeof a&&("object"!==typeof a||"number"!==typeof a.length))throw Error("JSON.stringify");return h("",{"":c})})})();var H=function(){function a(c,h){if(null==c)return h.push("!n");if("number"===typeof c)return h.push("!"+c);if("string"===typeof c)return"\\"==c[c.length-1]?h.push("'"+c.replace(/'/g,"\\'")+"u005C'"):h.push("'"+c.replace(/'/g,"\\'")+"'");if("boolean"===typeof c)return h.push(c?"!t":"!f");if(c instanceof
Array){h.push("*");for(var b=0;b<c.length;b++)a(c[b],h);return h.push(")")}if("object"==typeof c){h.push("(");for(b in c)c.hasOwnProperty(b)&&(h.push(b),a(c[b],h));return h.push(")")}return h.push("!n")}return{stringify:function(c){var b=[];a(c,b);return b.join("")}}}(),P=a.ue_qsl||2E3,K=2E3,A=1===window.ue_ddq,n="foresterPayloadSize",y=function(){},f=e.JSON&&e.JSON.stringify||C&&C.stringify,S=H.stringify,b=a.ue||{},H=a.uet||y;(a.uet||y)("bb","ue_frst_v2",{wb:1});var g="//"+a.ue_furl+"/1/batch/1/OE/",
d=[],r=[],k=[],J=!1,Q,F,O=void 0===a.ue_hpfi?1E3:a.ue_hpfi,N=void 0===a.ue_lpfi?1E4:a.ue_lpfi,R={"scheduled-delivery":1},I=0,D=function(){function f(){if(e.XDomainRequest){var c=new XDomainRequest;c.onerror=y;c.ontimeout=y;c.onprogress=y;c.onload=y;c.timeout=0;return c}if(e.XMLHttpRequest){c=new XMLHttpRequest;if(!("withCredentials"in c))throw"";return c}if(e.ActiveXObject){for(var a=0;a<x.length&&!c;a++)try{c=new ActiveXObject(x[a]),x=[x[a]]}catch(b){}return c}}function c(c){for(var h=[],e=c[0]||
{},f=0;f<c.length;f++){var g={};g[c[f].c]=c[f].d;h.push(g)}return{rid:e.r||b.rid,sid:e.s||a.ue_sid,mid:e.m||a.ue_mid,mkt:e.mkt||a.ue_mkt,sn:e.sn||a.ue_sn,reqs:h}}function h(a){var b=c(a),h=f();if(!h)throw"";h.onerror=function(){for(var c=0;c<a.length;c++)d.push(a[c]);D.isSupported=!1};h.open("POST",g,!0);h.setRequestHeader&&h.setRequestHeader("Content-type","text/plain");b=L(b);h.send(b)}var x="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");
return{send:function(c){for(var a in c)c.hasOwnProperty(a)&&c[a].length&&h(c[a])},buildPOSTBodyLog:c,isSupported:!0}}(),E=function(){return{send:function(e){for(var c in e)if(e.hasOwnProperty(c)){for(var h=e[c],d=h,p={},u,q=0;q<d.length;q++)u=d[q].c,p[u]||(p[u]=[]),p[u].push(d[q]);h=h[0]||{};d=h.sn||a.ue_sn;h=g+(h.m||a.ue_mid)+":"+(h.s||a.ue_sid)+":"+(h.r||b.rid)+(d?":"+d:"");d=[];u=h;var q=[],l=void 0;for(l in p)if(p.hasOwnProperty(l))for(var k=0;k<p[l].length;k++){var m=p[l][k],n=encodeURIComponent((m.cs?
S:f)(m.d));q.push({l:n,t:m.t,p:1,c:l,d:m.cs?"c":"j"})}p=q;q=void 0;l="$";for(m=0;m<p.length;){k=p[m];q!=k.c?(u+=l+k.c+"\x3d",l="\x26",q=k.c):u+=",";var n=u,r=k.d+":",w=k;u=(w.l.match(".{1,"+(P-u.length)+"}[^%]{0,2}")||[])[0]||"";w.l=w.l.substr(u.length);u=n+(r+u+":"+k.t);if(k.l)u+=":"+k.p++ +"_",d.push(u),u=h,l="$",q=0;else if(m++,1!=k.p)for(u+=":"+k.p+"_"+k.p,n=0;n<k.p-1;n++)d[d.length-n-1]+=k.p}d.push(u);h=d;for(d=0;d<h.length;d++)(new Image).src=h[d]}},isSupported:!0}}(),M=function(){return{send:function(a){for(var c in a)if(a.hasOwnProperty(c)){var b=
D.buildPOSTBodyLog(a[c]),b=L(b);if(!navigator.sendBeacon(g,b))throw"";}},isSupported:!!navigator.sendBeacon}}();b._fic=E;b._fac=D;b._fbc=M;b._flq=d;b.sid=b.sid||a.ue_sid;b.mid=b.mid||a.ue_mid;b.furl=b.furl||a.ue_furl;b.sn=b.sn||a.ue_sn;b._flhs=b._flhs||0;b._lpn=b._lpn||{};try{e.amznJQ&&e.amznJQ.declareAvailable&&e.amznJQ.declareAvailable("forester-client"),e.P&&e.P.register&&e.P.register("forester-client",y)}catch(t){a.ueLogError(t,{logLevel:"WARN"})}(function(){b.log&&b.log.isStub&&(b.log.replay(function(a,
c,b){var e=a[2]||{};e.t=c;e.r=b;e.n=1;l(a[0],a[1],e)}),b.onunload.replay(function(a){r.push(a[0])}),b.onflush.replay(function(a){k.push(a[0])}))})();b.log=l;b.log.reset=function(){I=0};b.onunload=function(a){r.push(a)};b.onflush=function(a){k.push(a)};b.attach("beforeunload",B);b.attach("pagehide",B);H("ld","ue_frst_v2",{wb:1})})(ue_csm,window);
ue_csm.ue.exec(function(a,e){var v=function(){},m=function(){return{send:function(a,m){if(m&&a){var l;if(e.XDomainRequest)l=new XDomainRequest,l.onerror=v,l.ontimeout=v,l.onprogress=v,l.onload=v,l.timeout=0;else if(e.XMLHttpRequest){if(l=new XMLHttpRequest,!("withCredentials"in l))throw"";}else l=void 0;if(!l)throw"";l.open("POST",a,!0);l.setRequestHeader&&l.setRequestHeader("Content-type","text/plain");l.send(m)}},isSupported:!0}}(),z=function(){return{send:function(e,m){if(e&&m)if(navigator.sendBeacon(e,
m))a.ue_sbuimp&&a.ue&&a.ue.ssw&&a.ue.ssw("eelsts","scs");else throw"";},isSupported:!!navigator.sendBeacon&&!(e.cordova&&e.cordova.platformId&&"ios"==e.cordova.platformId)}}();a.ue._ajx=m;a.ue._sBcn=z},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(a,e){function v(){for(var a=0;a<arguments.length;a++){var b=arguments[a];try{var d;if(b.isSupported){var f=t.buildPayload(r,g);d=b.send(S,f)}else throw dummyException;return d}catch(k){}}y({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},e.ue_err_chan||"jserr")}function m(){if(g.length){for(var a=0;a<N.length;a++)N[a]();v(n._sBcn||{},n._ajx||{});g=[];d={};r={};I=D=k=J=0}}function z(){var a=new Date,b=function(a){return 10>
a?"0"+a:a};return Date.prototype.toISOString?a.toISOString():a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+String((a.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function w(a){try{return JSON.stringify(a)}catch(b){}return null}function G(a){try{return JSON.parse(a)}catch(b){}return null}function l(c,b,d,f){var l=!1;f=f||{};F++;F==H&&y({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",
logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},e.ue_err_chan||"jserr");var q;if(q=!(F>=H))(q=c&&-1<c.constructor.toString().indexOf("Object")&&b&&-1<b.constructor.toString().indexOf("String")&&d&&-1<d.constructor.toString().indexOf("String"))||Q++;q&&(c.producerId=c.producerId||b,c.schemaId=c.schemaId||d,c.timestamp=z(),b=Date.now?Date.now():+new Date,c.messageId=a.ue_id+"-"+b+"-"+F,f&&!f.ssd&&(c.sessionId=c.sessionId||a.ue_sid,c.requestId=c.requestId||a.ue_id,c.obfuscatedMarketplaceId=
c.obfuscatedMarketplaceId||a.ue_mid),(b=w(c))?(b=b.length,(g.length==P||k+b>K)&&m(),k+=b,c={data:t.compressEvent(c)},g.push(c),(f||{}).n?0===E?m():I||(I=e.setTimeout(m,E)):D||(D=e.setTimeout(m,M)),l=!0):l=!1);!l&&a.ue_int&&console.error("Invalid JS Nexus API call");return l}function B(){if(!R){for(var c=0;c<O.length;c++)O[c]();for(c=0;c<N.length;c++)N[c]();g.length&&(a.ue_sbuimp&&a.ue&&a.ue.ssw&&(c=w({dct:r,evt:g}),a.ue.ssw("eeldata",c),a.ue.ssw("eelsts","unk")),v(n._sBcn||{}));R=!0}}function L(a){O.push(a)}
function C(a){N.push(a)}var H=1E3,P=499,K=524288,A=function(){},n=a.ue||{},y=n.log||A,f=a.uex||A;(a.uet||A)("bb","ue_sushi_v1",{wb:1});var S=a.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",b=["messageId","timestamp"],g=[],d={},r={},k=0,J=0,Q=0,F=0,O=[],N=[],R=!1,I,D,E=void 0===a.ue_hpsi?1E3:a.ue_hpsi,M=void 0===a.ue_lpsi?1E4:a.ue_lpsi,t=function(){function a(b){d[b]||(d[b]="#"+J++,r[d[b]]=b);return d[b]}function e(a){if(a)switch(typeof a){case "number":return!(isNaN(a)||
Infinity===a)&&a.toString().length>("#"+J).length;case "boolean":break;case "string":return a.length>("#"+J).length;default:return!0}return!1}function f(d){if(e(d)){var g=0;d instanceof Array?g=2:d instanceof Function?g=0:d instanceof Object&&(g=1);switch(g){case 0:d=a(d);break;case 2:var k=d;d=[];for(var g=k.length,l=0;l<g;l++)d[l]=f(k[l]);break;case 1:g={};for(k in d)d.hasOwnProperty(k)&&(g[a(k)]=-1==b.indexOf(k)?f(d[k]):d[k]);d=g}}return d}return{compressEvent:f,buildPayload:function(){return w({cs:{dct:r},
events:g})}}}();(function(){if(n.event&&n.event.isStub){if(a.ue_sbuimp&&a.ue&&a.ue.ssw&&a.ue.ssw("eeldata")){var b=G(a.ue.ssw("eeldata").val);b&&b.evt instanceof Array&&b.dct instanceof Object&&(g=b.evt,r=b.dct,g&&r&&((b=(a.ue.ssw("eelsts")||{}).val)&&"unk"===b&&m(),a.ue.ssw("eeldata","{}"),a.ue.ssw("eelsts","unk")))}n.event.replay(function(a){a[3]=a[3]||{};a[3].n=1;l.apply(this,a)});n.onSushiUnload.replay(function(a){L(a[0])});n.onSushiFlush.replay(function(a){C(a[0])})}})();n.attach("beforeunload",
B);n.attach("pagehide",B);n._cmps=t;n.event=l;n.event.reset=function(){F=0};n.onSushiUnload=L;n.onSushiFlush=C;try{e.P&&e.P.register&&e.P.register("sushi-client",A)}catch(c){a.ueLogError(c,{logLevel:"WARN"})}f("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);